name: aadhaar_kyc_mobile
description: A new Flutter project for Aadhaar KYC.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0
  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.1
  image_picker: ^1.1.2
  file_picker: ^10.3.10
  path_provider: ^2.1.2
  image: ^4.1.3
  intl: ^0.19.0
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
